version: '2'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_DB=strapi
    ports:
      - "5435:5432"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always
